### ISSUE TITLE
5.bugfix: Optional vizsgálatának megszüntetése nullal(2)

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#10]
A feladatot végezte: Shalanky Yudot

A aLit.getLanguage() függvény eredménye optional, vagyis vagy van eredméyne vagy nincs. Az if-en belül aLit.getLanguage() == null kifejezést használunk, ami nem megfelelő. Használt megoldás az isPresent() függvény false értékének vizsgálása.

**Comment by nagyszabina** [comment]
hozzátartozó pull request:
