### ISSUE TITLE
6.bugfix: Optional értékének felhasználása vizsgálattal

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#11]
A feladatot végezte: Shalanky Yudot

A Statements.java fájlban theLiteral.getLanguage() visszatérési értékét rögtön fel szeretnénk használni, még az előtt, hogy megvizsgálnánk, hogy biztosan van-e egyáltalán értéke. Ezért az ifen belül azt is meg kell vizsgálnunk.

**Comment by nagyszabina** [comment]
hozzátartozó pull request:
