### ISSUE TITLE
7.bugfix: Optional értékének felhasználása vizsgálattal(2)

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#12]
A feladatot elvégezte: Shalanky Yudit

A Models2.java fájlon belül megpróbáljuk felhasználni a aRest.get() értékét anélkül, hogy megvizsgálnánk, hogy egyáltalán van-e értéke. Ezért a művelet előtt egy isPresent() függvényt kell meghívni, melynek a true értékét vizsgáljuk.

**Comment by nagyszabina** [comment]
hozzátartozó pull request:
