### ISSUE TITLE
Statikus analízis eszköz bekötése

### ISSUE THREAD

**Issue by VM9797** [BME-MIT-IET/Atlantide-iet-2019#2]
SonarQube bekötése
A feladatot végzi: Villányi Máté

**Comment by VM9797** [comment]
A SonarQube működéséhez szükséges a SonarQube kliens futása. Ez elérhető innen:
https://www.sonarqube.org/downloads/

A letöltött állomány kicsomagolása után CMD-ből kell a bin mappa megfelelő almappájából (os + bit) a StartSonar-t futtatni, majd ha elindult:
jvm 1    | 2019.05.02 18:25:35 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
Akkor utána 'gradle sonarqube' futtatása a lokális projekten, localhost:9000-en látható az eredmény.

**Comment by VM9797** [comment]
SonarQube kiinduló állapota:
https://i.imgur.com/y9CvBxu.png

**Comment by Judiiith** [comment]
SonarQube másik állapota: 
![image](https://user-images.githubusercontent.com/26506401/57134531-b890b200-6da6-11e9-9d56-ab9bd58cf99a.png)

**Comment by VM9797** [comment]
Pull request: https://github.com/BME-MIT-IET/Atlantide-iet-2019/pull/5
