### ISSUE TITLE
2.bugfix: isPresent() függvény megfelelő használata

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#7]
A feladatot végezte: Shalanky Yudit

A getLanguage() függvény visszatérési értéke optional , tehát van olyan eset amikor ennek nincs visszatérési értéke (nem null). Az appenden belül helytelenül vizsgáljuk meg ennek az értékét, szükséges az isPresent() és get() eredményeket külön kezelnünk.

**Comment by nagyszabina** [comment]
hozzátartozó pull request: https://github.com/BME-MIT-IET/Atlantide-iet-2019/pull/14
