### ISSUE TITLE
3.bugfix: isPresent() függvény megfelelő használata (2)

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#8]
A feladatot végezte: Shalanky Yudit

A append függvényen belül szintén optional értéket vizsgálunk helytelenül. 
Külön kell vizsgálni az optionalt isPresent és get() függvényekkel, még mielőtt felhasználnánk azok értékeit.

**Comment by nagyszabina** [comment]
hozzátartozó pull request:
