### ISSUE TITLE
4.bugfix: Optional vizsgálatának megszüntetése nullal

### ISSUE THREAD

**Issue by Judiiith** [BME-MIT-IET/Atlantide-iet-2019#9]
A feladatot végezte: Shalanky Yudot

A aLit.getLanguage() függvény eredménye optional, vagyis vagy van eredméyne vagy nincs. Az append függvényen belül null-al vizsgáljuk az értéket, ami nem helyes. Null-checket kell lecserélni az optional értékre.

**Comment by nagyszabina** [comment]
hozzátartozó pull request:
